import { sidebar } from 'vuepress-theme-hope';

export default sidebar({
  '/basic_language/': [
    {
      text: 'HTML',
      icon: 'html5 fa-brands',
      prefix: 'HTML/',
      children: 'structure',
      collapsible: true,
    },
    {
      text: 'CSS',
      icon: 'css3-alt fa-brands',
      prefix: 'CSS/',
      children: 'structure',
      collapsible: true,
    },
    {
      text: 'JavaScript',
      icon: 'js fa-brands',
      prefix: 'javaScript/',
      children: 'structure',
      collapsible: true,
    },
    {
      text: '预处理语言',
      icon: 'sass fa-brands',
      prefix: 'preprocess/',
      children: 'structure',
      collapsible: true,
    },
    {
      text: '框架',
      icon: 'vuejs fa-brands',
      prefix: 'vue/',
      children: 'structure',
      collapsible: true,
    },
    {
      text: 'Jquery',
      icon: 'jQuery',
      prefix: 'jquery/',
      children: 'structure',
      collapsible: true,
    },
  ],
  '/algorithm/': [
    {
      text: '数据结构',
      icon: 'sitemap fas',
      prefix: 'data_structure/',
      children: 'structure',
      collapsible: true,
    },
    {
      text: '手写练习',
      icon: 'pen-to-square fas',
      prefix: 'method_mock/',
      children: 'structure',
      collapsible: true,
    },
    {
      text: '解决方案',
      icon: 'box-archive fas',
      prefix: 'solution/',
      children: 'structure',
      collapsible: true,
    },
  ],
  '/Server/': 'structure',
  '/Efficiency/': 'structure',
  '/source_code/': [
    {
      text: 'Lodash',
      prefix: 'lodash/',
      children: 'structure',
      collapsible: true,
    },
    {
      text: 'promise',
      prefix: 'promise/',
      children: 'structure',
      collapsible: true,
    },
    {
      text: 'vue2',
      icon: 'vuejs fa-brands',
      prefix: 'vue2/',
      children: 'structure',
      collapsible: true,
    },
    {
      text: 'vue3',
      icon: 'vuejs fa-brands',
      prefix: 'vue3/',
      children: 'structure',
      collapsible: true,
    },
    {
      text: 'vue生态',
      icon: 'vuejs fa-brands',
      prefix: 'vue_related/',
      children: 'structure',
      collapsible: true,
    },
  ],
  '/browser_internet/': [
    {
      text: '浏览器',
      icon: 'chrome fa-brands',
      prefix: 'Browser/',
      children: 'structure',
      collapsible: true,
    },
    {
      text: '网络通信',
      icon: 'globe fas',
      prefix: 'network/',
      children: 'structure',
      collapsible: true,
    },
  ],
  '/paper/': [
    {
      text: 'pytorch',
      prefix: 'code/',
      children: 'structure',
      collapsible: true,
    },
    {
      text: '公考笔记',
      icon: 'user-graduate fas',
      prefix: 'exam/',
      children: 'structure',
      collapsible: true,
    },
  ],
  // '/Project_50/': 'structure',
  '/reference/': 'structure',
});
